// Generated by Rcpp::compileAttributes() -- do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// build_passport
List build_passport(String object_id, String rds_self, String animal_id, String species, String sex, String age, String condition, String tissue, String project, String researcher, String date, String notes, String parent_id, String rds_parent, CharacterVector lineage, CharacterVector children, CharacterVector rds_children, CharacterVector custom_keys, CharacterVector custom_vals);
RcppExport SEXP _seuratPassport_build_passport(SEXP object_idSEXP, SEXP rds_selfSEXP, SEXP animal_idSEXP, SEXP speciesSEXP, SEXP sexSEXP, SEXP ageSEXP, SEXP conditionSEXP, SEXP tissueSEXP, SEXP projectSEXP, SEXP researcherSEXP, SEXP dateSEXP, SEXP notesSEXP, SEXP parent_idSEXP, SEXP rds_parentSEXP, SEXP lineageSEXP, SEXP childrenSEXP, SEXP rds_childrenSEXP, SEXP custom_keysSEXP, SEXP custom_valsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< String >::type object_id(object_idSEXP);
    Rcpp::traits::input_parameter< String >::type rds_self(rds_selfSEXP);
    Rcpp::traits::input_parameter< String >::type animal_id(animal_idSEXP);
    Rcpp::traits::input_parameter< String >::type species(speciesSEXP);
    Rcpp::traits::input_parameter< String >::type sex(sexSEXP);
    Rcpp::traits::input_parameter< String >::type age(ageSEXP);
    Rcpp::traits::input_parameter< String >::type condition(conditionSEXP);
    Rcpp::traits::input_parameter< String >::type tissue(tissueSEXP);
    Rcpp::traits::input_parameter< String >::type project(projectSEXP);
    Rcpp::traits::input_parameter< String >::type researcher(researcherSEXP);
    Rcpp::traits::input_parameter< String >::type date(dateSEXP);
    Rcpp::traits::input_parameter< String >::type notes(notesSEXP);
    Rcpp::traits::input_parameter< String >::type parent_id(parent_idSEXP);
    Rcpp::traits::input_parameter< String >::type rds_parent(rds_parentSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type lineage(lineageSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type children(childrenSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type rds_children(rds_childrenSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type custom_keys(custom_keysSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type custom_vals(custom_valsSEXP);
    rcpp_result_gen = Rcpp::wrap(build_passport(object_id, rds_self, animal_id, species, sex, age, condition, tissue, project, researcher, date, notes, parent_id, rds_parent, lineage, children, rds_children, custom_keys, custom_vals));
    return rcpp_result_gen;
END_RCPP
}

// build_log_entry
List build_log_entry(String step, int n_cells, int n_genes, List params);
RcppExport SEXP _seuratPassport_build_log_entry(SEXP stepSEXP, SEXP n_cellsSEXP, SEXP n_genesSEXP, SEXP paramsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< String >::type step(stepSEXP);
    Rcpp::traits::input_parameter< int >::type n_cells(n_cellsSEXP);
    Rcpp::traits::input_parameter< int >::type n_genes(n_genesSEXP);
    Rcpp::traits::input_parameter< List >::type params(paramsSEXP);
    rcpp_result_gen = Rcpp::wrap(build_log_entry(step, n_cells, n_genes, params));
    return rcpp_result_gen;
END_RCPP
}

// append_log_entry
List append_log_entry(List log, List new_entry);
RcppExport SEXP _seuratPassport_append_log_entry(SEXP logSEXP, SEXP new_entrySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type log(logSEXP);
    Rcpp::traits::input_parameter< List >::type new_entry(new_entrySEXP);
    rcpp_result_gen = Rcpp::wrap(append_log_entry(log, new_entry));
    return rcpp_result_gen;
END_RCPP
}

// validate_passport
bool validate_passport(List passport);
RcppExport SEXP _seuratPassport_validate_passport(SEXP passportSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type passport(passportSEXP);
    rcpp_result_gen = Rcpp::wrap(validate_passport(passport));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_seuratPassport_build_passport",   (DL_FUNC) &_seuratPassport_build_passport,   19},
    {"_seuratPassport_build_log_entry",  (DL_FUNC) &_seuratPassport_build_log_entry,   4},
    {"_seuratPassport_append_log_entry", (DL_FUNC) &_seuratPassport_append_log_entry,  2},
    {"_seuratPassport_validate_passport",(DL_FUNC) &_seuratPassport_validate_passport, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_seuratPassport(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
