# Generated by Rcpp::compileAttributes() -- do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

build_passport <- function(object_id, rds_self, animal_id, species, sex, age,
                           condition, tissue, project, researcher, date, notes,
                           parent_id, rds_parent, lineage, children,
                           rds_children, custom_keys, custom_vals) {
    .Call("_seuratPassport_build_passport", PACKAGE = "seuratPassport",
          object_id, rds_self, animal_id, species, sex, age, condition,
          tissue, project, researcher, date, notes, parent_id, rds_parent,
          lineage, children, rds_children, custom_keys, custom_vals)
}

build_log_entry <- function(step, n_cells, n_genes, params) {
    .Call("_seuratPassport_build_log_entry", PACKAGE = "seuratPassport",
          step, n_cells, n_genes, params)
}

append_log_entry <- function(log, new_entry) {
    .Call("_seuratPassport_append_log_entry", PACKAGE = "seuratPassport",
          log, new_entry)
}

validate_passport <- function(passport) {
    .Call("_seuratPassport_validate_passport", PACKAGE = "seuratPassport",
          passport)
}
